# This dockerfile is used within the GitHub Actions workflow to build the Docker image,
# and uses the build-artifacts directory to copy the build files to the nginx image.
FROM nginx:1.17.1-alpine
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY dist/tovedem-reserveringen/browser /usr/share/nginx/html
EXPOSE 80