# This dockerfile is used within the GitHub Actions workflow to build the Docker image,
# and uses the build-artifacts directory to copy the build files to the nginx image.
FROM node:22.3-alpine AS build
WORKDIR /usr/src/app
COPY build-artifact .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/build-artifacts /usr/share/nginx/html
EXPOSE 80